# config/_default/menus.yaml

# -----------------------------------------------
# English Menu (en)
# -----------------------------------------------
en:
  - name: Tour
    url: tour/
    weight: 10
  - name: News
    url: post/
    weight: 20
  - name: People
    url: people/
    weight: 30
  - name: Events
    url: event/
    weight: 40
  - name: Publications
    url: publication/
    weight: 50
  - name: Contact
    url: contact/
    weight: 60

# -----------------------------------------------
# Chinese Menu (zh)
# -----------------------------------------------
zh:
  - name: 概览
    url: tour/
    weight: 10
  - name: 动态
    url: post/
    weight: 20
  - name: 团队
    url: people/
    weight: 30
  - name: 活动
    url: event/
    weight: 40
  - name: 论文
    url: publication/
    weight: 50
  - name: 联系方式
    url: contact/
    weight: 60